# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e902d80c4f97260134b51363d0044c124f85e2e185b7b1beb15bac15e0f2025d14ffa46cdc989003a4bb0824c474453da662633afb563aa01f8dede01143fe6

test:
  secret_key_base: de35307a102e6607f22dfcd51b3df621435613f74640be05077d09a3ee2ddbbffda1d8ae73eb431ccf4d9348a2b0c127451e902394a788fd51d1b0100c52bc18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
